// <auto-generated />
namespace CRMSanto.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class KlantRelatieFinalCountDown : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(KlantRelatieFinalCountDown));
        
        string IMigrationMetadata.Id
        {
            get { return "201506170902192_KlantRelatie-FinalCountDown"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
