// <auto-generated />
namespace CRMSanto.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RelatiesFinal5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RelatiesFinal5));
        
        string IMigrationMetadata.Id
        {
            get { return "201506121008185_Relaties-Final5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
