// <auto-generated />
namespace CRMSanto.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class KlantRelatieTweaks3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(KlantRelatieTweaks3));
        
        string IMigrationMetadata.Id
        {
            get { return "201506161936250_KlantRelatie-Tweaks3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
